name: Qodana
on:
  workflow_dispatch:
  push:
  pull_request:
      branches: [ "master" ]
  
jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2023.2
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
  mc-publish:
      runs-on: ubuntu-latest
      steps:
        - name: 'MC Publish'
          uses: Kir-Antipov/mc-publish@v3.3
          with:
            modrinth-id: lS2PKjpV
            modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
